### ISSUE TITLE
Add support for `.default`

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/cddl-codegen#42]
Currently, when a required field is missing we generate code that looks like this

```
let key_0 = match key_0 {
    Some(x) => x,
    None => return Err(DeserializeFailure::MandatoryFieldMissing(Key::Uint(0)).into()),
};
```

I believe for `.default`, all the code is generated exactly as it is now except we change this error to instead return the default value.

Additionally, on serialization, if the field is equal to the default value we just omit it from the cbor notation

This is used in one place in the byron CDDL spec (although `byron.cddl` does not mention it)

**Comment by rooooooooob** [comment]
@SebastienGllmt  Note that according to the CDDL RFC:

>  This control is
>  only meaningful when the control type is used in an optional context;
>  otherwise, there would be no way to make use of the default value.

I interpreted this as meaning that the code at the top of this issue should stay the same as that's only for mandatory fields. For optional fields we would use the default value though. The governance cip uses it on an optional field. I can't tell for the byron one since I only have the one that doesn't mention it.
