### ISSUE TITLE
Order definitions via a dependency graph

### ISSUE THREAD

**Issue by SebastienGllmt** [dcSpark/cddl-codegen#93]
Currently, we parse rules as they come doing multiple passes. It would be nice if we instead generated a dependency graph of rules and then parsed rules based on this graph

**Comment by rooooooooob** [comment]
We'll need to handle cycles for recursive types in some way e.g. 'plutus_data` which references `plutus_list` which references `plutus_data`. IIRC how it is now we need to hand edit it due to the const variant (since it contains a single datum which leads to undefined type sizes in rust) by making it a box but it's fine for maps/lists since those are already normally heap allocated.
